addSbtPlugin("org.scala-js"      % "sbt-scalajs"         % "1.2.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.18.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.9.20")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.6.0")
