addSbtPlugin("org.scala-js"      % "sbt-scalajs"         % "1.13.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.20.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.14.3")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.9.0")
