addSbtPlugin("org.scala-js"      % "sbt-scalajs"         % "0.6.32")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.14.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.3.3")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.9.13")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.5.0")
